language: go
go:
  - 1.6.2
install:
  - echo noop
script:

  - go get -u github.com/golang/lint/golint
  - golint ./...
  - make test
  - test `gofmt -l . | wc -l` = 0
before_install:
  - go get github.com/mitchellh/gox
  - go get github.com/tcnksm/ghr
  - go get github.com/davecgh/go-spew/spew
  - go get github.com/hashicorp/logutils
  - go get -u github.com/kardianos/govendor
  - govendor sync
after_success:
  - make ci
  - ghr --username prudhvitella --token $GITHUB_TOKEN --delete --prerelease --debug pre-release dist/
branches:
  only:
    - master
