language: go
go:
  - 1.9
install:
  - echo noop
script:
  - go get -u golang.org/x/lint/golint
  - golint ./...
  - make test
before_install:
  - go get github.com/mitchellh/gox
  - go get github.com/tcnksm/ghr
  - go get github.com/davecgh/go-spew/spew
  - go get github.com/hashicorp/logutils
  - go get -u github.com/fanatic/go-infoblox
  - go get -u github.com/kardianos/govendor
  - govendor sync
after_success:
  - make ci
  - ghr --username prudhvitella --token $GITHUB_TOKEN --delete --prerelease --debug pre-release dist/
branches:
  only:
    - master
